const ROLES = {
  ADMIN: 'Administrator',
  PROCUREMENT_MANAGER: 'Procurement Manager',
  INVENTORY_PLANNER: 'Inventory Planner',
  WAREHOUSE_USER: 'Warehouse User',
  SUPPLIER: 'Supplier',
  FINANCE_REVIEWER: 'Finance Reviewer',
  FIELD_OFFICER: 'Field Officer',
  AGRONOMIST: 'Agronomist',
  FARMER: 'Farmer',
  VIEWER: 'Viewer'
};

const PERMISSIONS = {
  // Inventory
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE: 'inventory:manage',
  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_TRANSFER: 'inventory:transfer',

  // Procurement
  PROCUREMENT_VIEW: 'procurement:view',
  PROCUREMENT_CREATE_REQUEST: 'procurement:create_request',
  PROCUREMENT_APPROVE_REQUEST: 'procurement:approve_request',
  PROCUREMENT_CREATE_PO: 'procurement:create_po',
  PROCUREMENT_APPROVE_PO: 'procurement:approve_po',
  PROCUREMENT_RECEIVE: 'procurement:receive',

  // Forecasting & AI
  FORECAST_VIEW: 'forecast:view',
  FORECAST_RUN: 'forecast:run',
  AI_RECOMMENDATION_VIEW: 'ai:recommendation_view',
  AI_RECOMMENDATION_DECIDE: 'ai:recommendation_decide', // Approve/Reject/Override

  // Suppliers
  SUPPLIER_VIEW: 'supplier:view',
  SUPPLIER_MANAGE: 'supplier:manage',

  // Farmers
  FARMER_VIEW: 'farmer:view',
  FARMER_MANAGE: 'farmer:manage',

  // System & Admin
  USER_MANAGE: 'user:manage',
  AUDIT_VIEW: 'audit:view',
  SETTINGS_MANAGE: 'settings:manage',
  REPORTS_VIEW: 'reports:view'
};

const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PROCUREMENT_MANAGER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE_REQUEST,
    PERMISSIONS.PROCUREMENT_APPROVE_REQUEST,
    PERMISSIONS.PROCUREMENT_CREATE_PO,
    PERMISSIONS.PROCUREMENT_APPROVE_PO,
    PERMISSIONS.PROCUREMENT_RECEIVE,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.FORECAST_VIEW,
    PERMISSIONS.AI_RECOMMENDATION_VIEW,
    PERMISSIONS.AI_RECOMMENDATION_DECIDE,
    PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.INVENTORY_PLANNER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_CREATE_REQUEST,
    PERMISSIONS.FORECAST_VIEW,
    PERMISSIONS.FORECAST_RUN,
    PERMISSIONS.AI_RECOMMENDATION_VIEW,
    PERMISSIONS.AI_RECOMMENDATION_DECIDE,
    PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.WAREHOUSE_USER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_RECEIVE
  ],
  [ROLES.SUPPLIER]: [
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.PROCUREMENT_VIEW
  ],
  [ROLES.FINANCE_REVIEWER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PROCUREMENT_VIEW,
    PERMISSIONS.PROCUREMENT_APPROVE_PO,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.FIELD_OFFICER]: [
    PERMISSIONS.FARMER_VIEW,
    PERMISSIONS.FARMER_MANAGE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  [ROLES.AGRONOMIST]: [
    PERMISSIONS.FARMER_VIEW,
    PERMISSIONS.FARMER_MANAGE,
    PERMISSIONS.FORECAST_VIEW
  ],
  [ROLES.FARMER]: [
    PERMISSIONS.FARMER_VIEW,
    PERMISSIONS.INVENTORY_VIEW
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.FORECAST_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  DEFAULT_ROLE_PERMISSIONS
};
